name: C++ CI

on:
  push:
    branches: [ main, ci_test ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Compile code
      run: make
      
    - name: Run program
      run: ./calculator
